[pytest]
testpaths = tests/unit tests/integration
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning:fastapi
    ignore::DeprecationWarning:jose
    ignore::DeprecationWarning:sqlalchemy
    ignore::DeprecationWarning:starlette
